---
title: On diapers and differential equations - the challenges of combining higher
  education and parenthood
author: "Gustav Lundberg"
date: "September 10, 2018"
output:
  html_document: default
  pdf_document: default
documentclass: article
classoption: a4paper
bibliography: 732A60litterature.bib
---

# Introduction

Higher education is traditionally pursued during the earlier twenties, in Sweden as well as internationally. Some students however, decide to do things in a slightly less common order and start a family before enrolling in university studies. This paper will attempt to give an overview of the differences between traditional students and students combining parenthood and studies as well as discuss the necessity and benefits of attracting such students to higher education. 

# Previous Research

In Sweden, the number if students receiving extra support the Swedish Board of Student Finance for having children amounts to around 80 000 persons, which should be considered a lower threshold since some students combine work and studies thus not being eligble for student loans. While these students may not struggle to get up in time for lectures or wonder if the pasta or the water goes first^[True story, question asked during general discussion in my first year at University], they face other challenges in their daily lives and may require different kinds of support from faculty as well as family to maximize the chances of persisting to the point of obtaining a degree.

The research done on the subject can be divided into international - often US-centric - studies and research on the somewhat special and equality driven Swedish higher education system. Many studies regard adult learners or older students in general and although parenting students are generally at a higher than average age, they are not entirely a subset of adult learners. The challenges, benefits and adaptations mentioned below are those that I have seen no reason to differ from the respective study's target group and parenting students.

## International studies

### Differences percieved by students
Dill and Henley [-@DillHenley_Stressors] studied how different types of events affected the percieved stress of traditional and non-traditional US students, i.e. students with a break between high-school and college as well as having responsibilities apart from the studies such as parenthood or employment. The authors found several differences between the two groups. Amongst others, the non-traditional students felt less anxiety over not performing well enough and also enjoyed attending class to a greater extent than the traditional students, albeit attending class to a lesser degree than their traditional counterparts. It is speculated that this may be an indication being able to attain satisfaction from multiple roles and I would personally agree that there is a certain satisfaction to be had when one is able to pick the kids up earlier than planned from kindergarten after passing an exam.

Dill and Henley went on to discuss the dissimilarities in the types of social networking between the groups, that traditional students spent more time on and were more affected by the interaction with their peers. The parents' expectations to show results were also reported to be a greater source of stress for the tradional than the non-traditional students, something that is not seen as surprising as the parents of the surveyed students would normally be the ones paying for the education. These findings could be seen as further proof that the non traditional students have more sources from which they may gain satisfaction all the while having less time for each individual source.

Although the above findings were documented some 20 years ago, later research summarized by Brinhapt and Eady [-@BrinhauptEady_Attitudes] in their article on faculty members' attitudes largely seem to agree with Dill and Henley. 

### Differences perceived by teachers
Brinhaupt and Eady's research [-@BrinhauptEady_Attitudes] takes a look at the opposite side of things and survey how teachers and staff act towards non-traditional students and specifically how these interactions differed from interactions with traditional students, ie students below the age of 25. It was found that teachers generally appreciate the mix of student ages and perceive few, if any,  negative effects of having older students in class. An interesting note is that the adult learners were seen as more grade conscious by the teachers. This goes somewhat against the findings of Dill and Henley [-@DillHenley_Stressors] that non-traditional students were less stressed by performance expectations, but can also be interpreted as supporting the non-traditional students ability to gather positives from multiple sources.

The teachers surveyed by Brinhaupt and Eady had generally not made any special arrangements for their older students, nor felt any need to do so. Those teachers who had made arrangements reported a more positive attitude to older students and also a greater interest in learning more on how these students function. On a less positive note it should be mentioned that special arrangements could include adaptations geared towards capitalizing on the special experience that older students may posess, thus potentially missing out on adding value to all students. Avoiding classroom adaptions may also be the results of not wanting to risk discrimination on any part of the student body. It should also be stressed that the definitions of non-traditional students differ between the two studies mentioned so far.

### The institutions' role in assuring student success
Mark Fincher [-@Fincher_Retention] widends the net and discuss how the universities as a whole can work for the benefit of older age students. He proposed the use of something called *Learning Enhancement* revolving around the idea that the pace of the learning process should be increased and presented a number of keys to making this a viable method in ensuring for retaining students. The method should not be confused with simply shortening the time of the education while retaining the same curriculum, but rather making the learning happen in a shorter amount of time. Among other things Fincher mentioned the need to ensure that knowledge deficiencies are handled and resolved rather than the student simply skipping parts of the education. This coupled with a more individual attention to academic performance will of course benefit most student, but older students with more diverse backgrounds may experience the greatest benefits. Other key elements in ensuring the likelihood of retaining an adult student included adaptations to the administrative elements of the institutions including synchronization of tuition payments and course schedule to make sure that the need for a course coincides with the possibility to finance it. 

Institutional encouragement was also brought forward as a key factor of adult student success in a study by Bergman et al [-@Bergman_Life] fittingly titled "If Life Happened but a Degree Didn't". Althought the logistic model used in the study didn't achieve significance on all the variables concerned with campus environment, the authors point out that controlling for these variables greatly increased the amount of variation in student persistance accounted for. The study also conludes that the support from close family and financial factors are important when ensuring that older students finish their education.

## Swedish research

While the amount of research focusing on Swedish students with multiple responsibilities are naturally fewer, one paper by Hallberg et al. [-@Hallberg_kids] made on behalf of the Institiute of Labour Market Policy Evaluation studied students that are also parents. This study discussed the effect on higher studies that nowadays stretch into the age were family was previously normally formed. The increased lifespan and expected years in work leads to a longer period from which the costs of education can be repaid while enabling people to enter higher studies after becoming parents can decrese medical costs for society compared to delaying the children until after university studies. All in all it may be benefitial for all of society to ensuring that the non-traditional student is a viable option to its citizens.

Hallberg's study focused among others on whether there are differences in study pace and student attirition between students that are parents and traditonal students. It was noted in several places that care should be taken when interpreting the models used as causal relationships since the subset of people that manage to graduate while being parents are likely special in more ways than just being parents, among other factors it was noted that female students made up over 70 percent of studying parents while their share among non-parents was only around 55 percent.

The study found that students with kids seemed to take slightly less time to graduate, but this is largely caused by those students who became parents during their studies and not those that entered studies already being parents. It was speculated that this may be caused by the financial uncertanty caused by having an unfinished degree, pushing students to speed up their studies once they became parents. Parents also seem to take less extracurricular courses than traditional students and have a higher likelihood of graduating, results that controlled for various background variables.

Hallberg and associates finally discussed the possibility that they were in fact dealing with two separate groups of students that combine studies with parenthood; one group that enter studies intent on actually graduating and another that see higher education as an alternative to unenployment. The generous swedish social security system is also suspected of playing a roll and enabling people to getting an income that the parental leave insurance is based on and only thereafter entering studies, effectively entering the labour market in a delayed manner.

# Personal reflections and discussion

As I am myself combining parenthood and higher studies I will have to agree with the research that there exists certain challenges with this combination. First and foremost this applies to the work that is to be done in association with other students. Non traditional students can choose to work with a (more) traditional student, carefully outlining the possible issues that co-op work may entail for the traditional student. In my experience this has always been the best option if group work is mandatory since the traditional student commonly have a less rigid private schedule and can easier accommodate short term changes on behalf of the non tradtional student. The latter of course have to responsive and inviting towards the former and not demand that the work is done only on his or her terms, something that is guaranteed to invoke poor group feeling.

Another option is of course to team up with another non traditional student but this require quite a lot of flexibility on both hands in order not to lead to status quos where the respective schedules clash and no time for cooperative work can be found. The risk of sudden change of plans that children entail does of course increase the risk that the team members take turns calling in sick for the duration of the project. Therefore, this solution should only be considered for projects that can safely be divided between the teammembers thus requiring a theoretical minimum of actual cooperation, but  perhaps benefiting greatly from any amount of time that can be spent cooperating. 

The last option is of course to request special treatment from the institution in one way or another, preferably by being allowed to do a group task by yourself. This has some obvious drawbacks and some slightly less obvious ones; most apparently that the amount of work that is required from the student is doubled (or thereabouts). Another less obvious complication is that the teacher is required to check a larger number of projects than planned for when accepting a certain number of students on a course. Furthermore, it may be seen as unfair by other students that the non traditional student does not have to handle the cooperative challenges that may occur in a project, or even worse, that the non traditional student does not have to complete the same task as others. This solution would likely only be considered in cases where the overhead of doing a group project by yourself is apparently much larger than the effort of setting up a smooth team work.

The amount of flexibility that a non traditional student can display to his or her peers is in my mind a key factor in the success in group efforts, surpassing expectations will generate an almost exponential amount of respect and flexibility from the counterparts. The back of the same coin is that demanding or requiring ones peers to always adapt to your situation will result in massively decreased willingness to do so. The finishing remarks of Hallberg et al. [-@Hallberg_kids] that the non traditional students that actually finish their degree are intent on doing so from the beginning would support this notion, if you know your limitations you make sure you also have ways of working around them. 

The financial aspects of being a student mentioned in the international studies are not always transferrable to Sweden where the tuition is free and all citizens below 50 years of age are guaranteed student loans and financing. For some non traditional students however, the student loans and financing needs to cover the children's expenses as well, and *Barnbidrag*^[General financial aid goven to the caretaker of every child below 16 years of age, SEK 1150/month], *Tilläggsbidrag*^[Financial aid given to students loan recievers that are caretakers of children, SEK 150/week] and other financial aids goes only so far when winter clothes, sports fees and birthday gifts are to be purchased. On the other hand, it can be discussed how much support should be given in the name of equal opportunities; children don't just appear in ones life, they are the result of conscious actions. 

The list of challenges for non traditional students can, as shown above, be long. Most of it however can be overcome by dialogue with ones peers and institution as well as the realisation that one may some unconventional prioritizing. May it be skipping a lecture to attend a parental meeting in school or doing most of your writing after the kids have fallen asleep, most things can be handled with some amount of planning. In the end, the benefit of actually finishing a grade will likely overshadow a couple of years of extra hard work.

# References
