---
title: "Test"
author: "Sridhar"
date: "September 20, 2018"
output: html_document
---
```{r}
library(ggplot2)
library(plotly)
library(xlsx)
library(MASS)
```

```{r}
bball = read.xlsx("baseball-2016.xlsx", sheetName = "Sheet1", header = TRUE,
                  row.names = 1)
head(bball)

#Q2
bball.numeric = bball[,3:27]
distance = dist(bball.numeric)
res = isoMDS(distance, k=2)
coords = res$points

coordsMDS = as.data.frame(coords)
coordsMDS$name = rownames(coordsMDS)
coordsMDS$league = bball$League
plot_ly(coordsMDS, x=~V1, y=~V2, type="scatter", mode = "markers"
        , hovertext=~name, color= ~league)


#Q3
sh <- Shepard(distance, coords)
delta <-as.numeric(distance)
D<- as.numeric(dist(coords))

n=nrow(coords)
index=matrix(1:n, nrow=n, ncol=n)
index1=as.numeric(index[lower.tri(index)])

n=nrow(coords)
index=matrix(1:n, nrow=n, ncol=n, byrow = T)
index2=as.numeric(index[lower.tri(index)])

plot_ly()%>%
  add_markers(x=~delta, y=~D, hoverinfo = 'text',
              text = ~paste('Obj1: ', rownames(bball)[index1],
                            '<br> Obj 2: ', rownames(bball)[index2]))%>%
  add_lines(x=~sh$x, y=~sh$yf)

#Q4
po = plot_ly(x=~coordsMDS$V1, y=~bball[, 4], type="scatter", mode = "markers"
        , hovertext=~rownames(bball))
print(po)
cols_bball = colnames(bball)
dim(bball)[2]
plots_bball = list()
for(i in 2:4){
  pl_name = paste("P", i)
  plots_bball[[pl_name]] = plot_ly(x=~coordsMDS$V1, y=~bball[,i], type="scatter", mode = "markers"
                                 , hovertext=~rownames(bball))
}
invisible(lapply(plots_bball, print))
```